const translations = {
    en: {
        txt1 : "this Web Site designed by :",
        txt2 : "1-Bakeel Ali Al_Edrisy",
        txt3 : "2-Khabab Abduo Al_Shahery ",
        txt4 : "3-Ragi Shaif Al_Sarawy",
        txt5 : "Home",
        txt6 : "Sections",
        txt7 : "University Courses ",
        txt8 : "Graduation projects",
        txt9 : "General Scientific",
        txt10 : "Cultural ",
        txt11 : "Eslamic",
        txt12 : "Historic ",
        txt13 : "Social and",
        txt14 : "Stories and novels ",
        txt15 : "Poems",
        txt16 : "Research and projects ",
        txt17 : "Spread",
        txt18 : "Puplish",
        txt19 : "Puplish Search",
        txt20 : "Puplish project",
        txt21 : "Create Acount",
        txt22 : "Log in",
        txt23 : "Home",
        txt24 : "Sections",
        txt25 : "University Courses",
        txt26 : "Graduation projects",
        txt27 : "General Scientific",
        txt28 : "Cultural",
        txt29 : "Eslamic",
        txt30 : "Historic",
        txt31 : "Social and",
        txt32 : "Stories and novels",
        txt33 : "Poems",
        txt34 : "Research and projects",
        txt35 : "Spread",
        txt36 : "Puplish ",
        txt37 : "Puplish Search",
        txt38 : "Puplish project",
        txt39 : "Create Acount",
        txt40 : "log in",
        txt41 : "Recearch",
        txt42 : "Translate to",
        txt43 : "English",
        txt44 : "Arabic",
        txt45 : "the outhers:",
        txt46 : "Khabab Al_Shahery ",
        txt47 : "Number of works",
        txt48 : "Ragi Al_Sarawy ",
        txt49 : "Number of works",
        txt50 : "Bakeel Al_Edrisy",
        txt51 : "Number of works",
        txt52 : "Khabab Al_Shahery ",
        txt53 : "Number of works",
        txt54 : "Khabab Al_Shahery",
        txt55 : "Number of works",
        txt56 : "Ragi  Al_Sarawy",
        txt57 : "Number of works",
        txt58 : "Bakeel Al_Edisy ",
        txt59 : "Number of works",
        txt60 : "the latest:",
        txt61 : "Summary date of time ",
        txt62 : "Mostafa Ibrahim Fahmy",
        txt63 : "O wake your capablities and make your future",
        txt64 : "Ibrahim Faqi",
        txt65 : "Success Story",
        txt66 : "Raowf Shababic ",
        txt67 : "Mind Journey",
        txt68 : "Amro Sharif",
        txt69 : "Summary date of time",
        txt70 : "Mostafa Ibrahm Fahmy",
        txt71 : "O wake your capablities and make your future",
        txt72 : "Ibrahim Faqi",
        txt73 : "Success Story",
        txt74 : "Rawof Shababic",
        txt75 : "Mind Journey",
        txt76 : "Amro Sharif ",
        txt77 : "Loding:",


        txt01 : "Summary date of time",
        txt02 : "Mostafa Ibrahim Fahmy",
        txt03 : "O wake your capablities and make your future",
        txt04 : "Ibrahim Faqi",
        txt05 : "Success Story",
        txt06 : "Raowf Shababic",
        txt07 : "Mind Journey",
        txt08 : "Amro Sharif",
        txt09 : "Summary date of time",
        txt010 : "Mostafa Ibrahm Fahmy",
        txt011 : "O wake your capablities and make your future",
        txt012 : "Ibrahim Faqi",
        txt013 : "Success Story",
        txt014 : "Rawof Shababic",
        txt015 : "Mind Journey",
        txt016 : "Amro Sharif",


        txt100 : "$0.00",
        txt101 : "$10.00",
        txt102 : "$9.50",
        txt103 : "$0.00",
        txt104 : "$0.00",
        txt105 : "$10.00",
        txt106 : "$9.50",
        txt107 : "$0.00",
        txt108 : "$0.00",
        txt109 : "$10.00",
        txt110 : "$9.50",
        txt111 : "$0.00",
        txt112 : "$0.00",
        txt113 : "$10.00",
        txt114 : "$9.50",
        txt115 : "$0.00",
        txt116 : " Convention",
        txt117 : "Privacy Policy",
        txt118 : "About US",
        txt119 : "Property rights",
        txt120 : "Call Us :",
        txt121 : "This web site designed by",
        txt122 : "Bakeel Al_Edrisy ",
        txt123 : "All rights reseved by Ibb UN",

    },
    ar: {
        txt1 : "تم تصمصم هذا المشروع بواسطة:",
        txt2 : "1- بكيل علي عبد الله الادريسي",
        txt3 : " 2- خباب عبد ناجي الشاهري ",
        txt4 : " 3- راجي شايف مثنى الساروي",
        txt5 : " الرئيسية",
        txt6 : "الأقسام",
        txt7 : "مقررات جامعية ",
        txt8 : "مشاريع تخرج",
        txt9 : "علمية عامة",
        txt10 : "ثقافية ",
        txt11 : "اسلامية",
        txt12 : "تاريخية ",
        txt13 : "اجتماعية",
        txt14 : "قصص وروايات",
        txt15 : "شعرية",
        txt16 : "ابحاث ومشاريع",
        txt17 : "نشر",
        txt18 : "نشر كتاب",
        txt19 : "نشر بحث",
        txt20 : "نشر مشروع",
        txt21 : "إنشاء حساب",
        txt22 : "تسجيل الدخول",
        txt23 : "الرئيسية",
        txt24 : "الأقسام",
        txt25 : "مقررات جامعية ",
        txt26 : "مشاريع تخرج",
        txt27 : "علمية عامة",
        txt28 : "ثقافية",
        txt29 : "اسلامية",
        txt30 : "تاريخية",
        txt31 : "اجتماعية",
        txt32 : "قصص وروايات",
        txt33 : "شعرية",
        txt34 : "ابحاث ومشاريع",
        txt35 : "نشر",
        txt36 : "نشر كتاب",
        txt37 : "نشر بحث",
        txt38 : "نشر مشروع",
        txt39 : "إنشاء حساب",
        txt40 : "تسجيل الدخول",
        txt41 : "بحث",
        txt42 : "ترجمة الى",
        txt43 : "انجليزية",
        txt44 : "عربية",
        txt45 : "المؤلفين :",
        txt46 : "خباب الشاهري ",
        txt47 : "عدد المؤلفات:",
        txt48 : "راجي الساروي ",
        txt49 : "عدد المؤلفات:",
        txt50 : "بكيل الادريسي",
        txt51 : " عدد المؤلفات:",
        txt52 : "خباب الشاهري ",
        txt53 : "عدد المؤلفات:",
        txt54 : "خباب الشاهري  ",
        txt55 : "عدد المؤلفات:",
        txt56 : " راجي الساروي ",
        txt57 : "عدد المؤلفات:",
        txt58 : "بكيل الادريسي",
        txt59 : "عدد المؤلفات:",
        txt60 : "الأحدث :",
        txt61 : "تاريخ موجز للزمن",
        txt62 : "مصطفى إبراهيم فهمي",
        txt63 : "ايقظ قدراتك واصنع مستقبلك",
        txt64 : "إبراهيم الفقي",
        txt65 : "قصة نجاح",
        txt66 : "رءوف شبايك",
        txt67 : "رحلة عقل",
        txt68 : "عمرو شريف",
        txt69 : "تاريخ موجز للزمن",
        txt70 : "مصطفى إبراهيم فهمي",
        txt71 : "ايقظ قدراتك واصنع مستقبلك",
        txt72 : "إبراهيم الفقي",
        txt73 : "قصة نجاح",
        txt74 : "رءوف شبايك",
        txt75 : "رحلة عقل",
        txt76 : "عمرو شريف",
        txt77 : "الأكثر تحميلا  :",
        // txt78 : "",
        // txt79 : "",


        txt01 : "تاريخ موجز للزمن",
        txt02 : "مصطفى إبراهيم فهمي",
        txt03 : "ايقظ قدراتك واصنع مستقبلك",
        txt04 : "إبراهيم الفقي",
        txt05 : "قصة نجاح",
        txt06 : "رءوف شبايك",
        txt07 : "رحلة عقل",
        txt08 : "عمرو شريف",
        txt09 : "تاريخ موجز للزمن",
        txt010 : "مصطفى إبراهيم فهمي",
        txt011 : "ايقظ قدراتك واصنع مستقبلك",
        txt012 : "إبراهيم الفقي",
        txt013 : "قصة نجاح",
        txt014 : "رءوف شبايك",
        txt015 : "رحلة عقل",
        txt016 : "عمرو شريف",


        txt100 : "$0.00",
        txt101 : "$10.00",
        txt102 : "$9.50",
        txt103 : "$0.00",
        txt104 : "$0.00",
        txt105 : "$10.00",
        txt106 : "$9.50",
        txt107 : "$0.00",
        txt108 : "$0.00",
        txt109 : "$10.00",
        txt110 : "$9.50",
        txt111 : "$0.00",
        txt112 : "$0.00",
        txt113 : "$10.00",
        txt114 : "$9.50",
        txt115 : "$0.00",
        txt116 : "اتفاقية الاستخدام",
        txt117 : "سياسة الخصوصية",
        txt118 : "عنا",
        txt119 : "حقوق الملكية",
        txt120 : "اتصل بنا :",
        txt121 : "صمم هذا الموقع بواسطة",
        txt122 : " بكيل الادريسي ",
        txt123 : "حقوق النشر والطبع محفوظة لداء جامعة إب",
    },
};




//export default translations;
//import translations from"./translationFile.js";




const languageSelector = document.querySelector("select");

languageSelector.addEventListener("change", (event) => {
    setLanguage(event.target.value);
    localStorage.setItem('lang', event.target.value);
});

document.addEventListener('DOMContentLoaded', () => {
    //const language = localStorage.getItem("lang");
    //setLanguage(language);
    setLanguage(localStorage.getItem("lang"));
});
const setLanguage = (language)=> {
    const elements = document.querySelectorAll("[data-i18n]");
    elements.forEach((element) => {
        const translationKey = element.getAttribute("data-i18n");
        element.textContent = translations[language][translationKey];
    });
    document.dir = language === "ar" ? "rtl" : "ltr";
};
